### ISSUE TITLE
no script is running

### ISSUE THREAD

**Issue by ghost** [marcusball/dashplus#1]
![immagine](https://cloud.githubusercontent.com/assets/15612297/10883580/34960946-8173-11e5-8895-49517c3f8655.jpg)

<img id="img_Tm8gc2NyaXB0IGlzIHJ1bm5pbmdfdW5kZWZpbmVk" class="icon16" src="chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/layout/default/images/info.png" name="No script is running" alt=" ?">

**Comment by marcusball** [comment]
Which script are you trying to run? Upload Photo For All Posts is out of date and unnecessary because Tumblr now has that included. 

If you're trying to use Follow Back Checker, I can try to look into the issue when I have some free time. It is worth noting, however, that, if FBC is still actually working correctly—I admittedly haven't maintained it for a while now—it will still only show up as running on www.tumblr.com/following, so make sure you're actually on that page when you look at running scripts.

**Comment by itsharris** [comment]
Hello, if it's possible can you please take a look at the FBC script for (Chrome) Tampermonkey. The script works on Firefox and the older versions of the scripts work on Chrome. For some reason, the latest script is not running on Chrome for a while. Thanks a bunch.
